//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "daily_summary")]
pub struct Model {
  pub customer_code: Option<i32>,
  pub member_code: Option<i32>,
  #[sea_orm(column_type = "Text", nullable)]
  pub visit_date: Option<String>,
  pub visit_time_period: Option<i32>,
  pub weixin_id: Option<i32>,
  pub pv: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
