//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "metadata_info")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
  pub column_name: String,
  #[sea_orm(column_type = "Text")]
  pub column_aliases: String,
  #[sea_orm(column_type = "Text")]
  pub column_type: String,
  pub is_nullable: i32,
  #[sea_orm(column_type = "Text", nullable)]
  pub column_default: Option<String>,
  #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
  pub table_name: String,
  #[sea_orm(column_type = "Text")]
  pub table_aliases: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
