//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "order_product_details")]
pub struct Model {
  pub customer_code: Option<i32>,
  #[sea_orm(column_type = "Text", nullable)]
  pub custormer_type: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub province: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub city: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub city_level: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub store_type: Option<String>,
  pub store_code: Option<i32>,
  pub custromer_code: Option<i32>,
  #[sea_orm(column_type = "Text", nullable)]
  pub baby_age_group: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub gender: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub crowd_type: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub online_order: Option<String>,
  #[sea_orm(column_name = "\r\npayment_date", column_type = "Text", nullable)]
  pub payment_date: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub write_off_date: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub associated_order_number: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub first_category: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub secondary_category: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub related_first_category: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub related_secondary_category: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub brand_name: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub related_brand_name: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub online_commodity_code: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub related_online_commodity_code: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub marketing_campaign_type: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub scene_name: Option<String>,
  pub payment_write_off_days_difference: Option<i32>,
  pub online_sales: Option<Decimal>,
  pub related_sales: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
