//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub use super::chat::Entity as Chat;
pub use super::daily_summary::Entity as DailySummary;
pub use super::message::Entity as Message;
pub use super::order_product_details::Entity as OrderProductDetails;
pub use super::user::Entity as User;
pub use super::vote::Entity as Vote;
