[package]
name = "common"
version = "0.1.0"
edition = "2024"
[dependencies]
zip = {workspace = true}
walkdir={workspace = true}
futures = {workspace = true}
tokio = {workspace = true}
tokio-util ={workspace = true}
archflow = {workspace = true}
